### ISSUE TITLE
Wallet error code: 51 Wallet error detail: You have not registered to use this API

### ISSUE THREAD

**Issue by mithilwcities** [android-pay/androidpay-quickstart#13]
I am getting following error for Android Pay in my Production App:

**Wallet error code: 51**
**Wallet error detail: You have not registered to use this API.**

This is happening while getting MaskedWallet class's instance from MaskedWalletRequest as mentioned in below code snippet:

**MaskedWalletRequest maskedWalletRequest = MaskedWalletRequest.newBuilder()
                        .setPaymentMethodTokenizationParameters(parameters)
                        .addAllowedCardNetworks(allowedCardNetworks)
                        .setMerchantName(AppConstants.MERCHANT_NAME)
                        .setCurrencyCode(currencyCode)
                        .setEstimatedTotalPrice(totalPrice + "")
                        .setCart(cart = generateCart(currencyCode))
                        .build();**

**Wallet.Payments.loadMaskedWallet(googleApiClient, maskedWalletRequest, AppConstants.MASKED_WALLET_REQUEST_CODE);**

After this the Android Pay Card chooser dialog appears for a moment and immediately it gets disappear after checking the logs, I am getting this : wallet error 51.

I have used Braintree as payment processor.

Is there anything I am missing? Any help is apprecieated

**Comment by samtstern** [comment]
@mithilwcities please do not post the same comment on many issues.

Have you signed up to be an Android Pay merchant using this form: https://support.google.com/androidpay/merchant/contact/api_interest?rd=1 ?

**Comment by mithilwcities** [comment]
yes, I have done that

**Comment by samtstern** [comment]
@mithilwcities I have reported this to the Android Pay team and we will try to find someone to help you with this issue.

**Comment by samtstern** [comment]
I think it's possible you may not be clear on the use of that interest form.  That form expresses your _interest_ in using Android Pay in production however the process is not instantaneous.  You should be notified when you are whitelisted.

In the future we hope to make this a quicker process.

**Comment by mklimek** [comment]
I've got exactly the same error.
Something has changed here?

**Comment by samtstern** [comment]
Thank you for taking the time to submit this issue, and I apologize that we never got around to solving it. I am closing this issue because the Android Pay API has been superseded by the Google Payments API.

This sample is deprecated and is no longer maintained. Please see the [paymentsapi-quickstart](https://github.com/android-pay/paymentsapi-quickstart) sample for an up-to-date sample.

If you believe your issue is relevant to that sample as well, please feel free to open a new issue there and we can continue discussing.
