### ISSUE TITLE
Error when switch ENVIRONMENT_TEST to ENVIRONMENT_SANDBOX

### ISSUE THREAD

**Issue by AmusementPark** [android-pay/androidpay-quickstart#17]
Hi. I'm OK to run the quick-start app when using ENVIRONMENT_TEST mode.
But while I change to ENVIRONMENT_SANDBOX mode, the android pay says I didn't attach a vaild card . I did nothing except for changing to ENVIRONMENT_SANDBOX mode. Is there any other configuration I need to change?

![screenshot_20160530-044357](https://cloud.githubusercontent.com/assets/9210003/15661853/13b8f732-271e-11e6-8ffc-563342cf5be1.png)
![screenshot_20160530-044806](https://cloud.githubusercontent.com/assets/9210003/15661854/13b9fb96-271e-11e6-9b34-7e79a51a50c2.png)

**Comment by AmusementPark** [comment]
I copied the most core payment code from quick-start to myself test app

**Comment by samtstern** [comment]
You should always be using `ENVIRONMENT_TEST`, the `SANDBOX` environment is used more for internal testing and may not be reliable.
