### ISSUE TITLE
 Android Pay App Test Account

### ISSUE THREAD

**Issue by gagan-utreja** [android-pay/androidpay-quickstart#24]
Android Pay App Downloaded from Google Play Store doesn't allow to add Credit Cards with sandbox credentials. Then how to test my app.
Can i get any card details for testing purpose. ?

**Comment by samtstern** [comment]
Sorry, right now there is no way to add test card details to Android Pay on your phone.  You will have to use a real card, however in the sandbox the payments / charges will not be real.
