### ISSUE TITLE
Can get card type?

### ISSUE THREAD

**Issue by lowfiend** [android-pay/androidpay-quickstart#29]
ex : Master or Visa

Can we?

**Comment by 8of** [comment]
@lowfiend 
`getInstrumentType()` function is what you are looking for.
You can get card type from Masked wallet like this:
`mMaskedWallet.getInstrumentInfos()[0].getInstrumentType()`
API reference: https://developers.google.com/android/reference/com/google/android/gms/wallet/InstrumentInfo.html#getInstrumentType()

But beware:
_This type **should not** be displayed to the user, but can be used when the details of a user's instrument are needed._ (from the DOCS)

**Comment by lowfiend** [comment]
@8ofproject  
Thank you.
