### ISSUE TITLE
Sample code contains case in the wrong switch-statement, will lead to errors

### ISSUE THREAD

**Issue by dimsuz** [android-pay/androidpay-quickstart#30]
`CheckoutActivity` has wrong logic: `case WalletConstants.RESULT_ERROR` is contained in the wrong switch statement and because of that it checks `requestCode` instead of `resultCode` as it should.

This may misguide developers and lead to errors in their apps with Android Pay integration.

Relevant lines of code could be [seen here](https://github.com/android-pay/androidpay-quickstart/blob/master/app/src/main/java/com/google/android/gms/samples/wallet/CheckoutActivity.java#L159-L162).

**Comment by samtstern** [comment]
@dimsuz thanks for catching this!  Would you like to submit a PR?

**Comment by dimsuz** [comment]
I might create a PR, but a bit later then. Quite busy right now. I noticed this error is also present in other activities/fragments (`ConfirmationActivity.java`).

**Comment by 8of** [comment]
@dimsuz thanks for pointing out the bug. 👍 
@samtstern can we close the issue?
My bad, I forgot to mention it with `fixes` keyword from commit. 🙏
