### ISSUE TITLE
Testing Example app: Request failed Error in loadMaskedWallet

### ISSUE THREAD

**Issue by ShkurtiA** [android-pay/androidpay-quickstart#31]
Hello,

I am trying to run the example app with the updated dependencies and gradle wrapper. 
When I run it and try to make a payment after pressing the button "buy with Android pay" an error dialog shows: 

> Request failed: An unexpected error has occurred. Please try again later.

 And after I press ok I see this message in the logs: 

`06-01 18:28:02.378 12251 12251 W WalletMerchantError: Error in loadMaskedWallet: Did you forget the set Android Pay testing environment to PROD?`

Before trying the example app I did my own example and this is the question I opened in stackoverflow with the same results and error: https://stackoverflow.com/questions/44305488/android-pay-error-in-loadmaskedwallet

Do you have any idea what the problem could be? I have tried in two different devices and 2 different cards

**Comment by 8of** [comment]
What's the type of card you have in Android Pay?
Is it **real card** or **test card** with generated number / CVC ?

If it's test card - you can try to replace all:
`WalletConstants.ENVIRONMENT_TEST`
in your code with:
`WalletConstants.ENVIRONMENT_SANDBOX`
You will (most probably) move one step further in android pay flow. But it's deprecated feature already, and it doesn't work very consistent anymore.

The best way to make it work: use **real card** with **ENVIRONMENT_TEST** constant.
In that case you won't be charged.

**Comment by 8ofproject** [comment]
According to your code on StackOverflow you moved GoogleApiClient builder to it's own function. But it's not clear if you actually call it or not?

**Comment by ShkurtiA** [comment]
I am using test cards provided from google or that can be found online. I am using `WalletConstants.ENVIRONMENT_TEST`  as the other is deprecated. 

First thing I want to know from this issue is, what is the meaning of the logs and the error code. Second thing is, how to fix it.

**Comment by 8of** [comment]
@ShkurtiA 
**Issue**: test cards (even the one provided by Google) don't work anymore (at least not outside of US);
**Solution**: you need real card to make it work. You won't be charged with `ENVIRONMENT_TEST`.

**Comment by ShkurtiA** [comment]
Ok I understand. Thank you for this hint. I will try to test also with a real card.
