### ISSUE TITLE
what is the xxd stand for ?  please . anybody could ans me

### ISSUE THREAD

**Issue by cnmao** [android-pay/androidpay-quickstart#34]

**Comment by cnmao** [comment]
echo $PUBLICKEY | xxd -r -p | base64

**Comment by 8of** [comment]
It's [hexdump](https://en.wikipedia.org/wiki/Hex_dump).
You can check available commands and explanation with `xxd -h`
For example:
`-r` - reverse hexdump into binary
`-p` - output in postscript continuous hexdump style

**Comment by samtstern** [comment]
Yep @8ofproject got it.

**Comment by cnmao** [comment]
thinks you two  - =
