### ISSUE TITLE
set the WalletOptions 'brand' field to ANDROID_PAY

### ISSUE THREAD

**Issue by MaTriXy** [android-pay/androidpay-quickstart#6]
Trying to use the Google sample app for Android Pay. 
I got the error in logcat:
**"To use this API, you must set the WalletOptions 'brand' field to ANDROID_PAY"**

```
10-16 10:32:33.564 26114-355/? E/Volley: [4806] BasicNetwork.performRequest: Unexpected response code 400 for https://wallet.google.com/payments/apis/instantbuy/android/v1/getWalletItems
10-16 10:32:33.568 26114-26667/? W/BaseAppContext: Using Auth Proxy for data requests.
10-16 10:32:33.584 21959-21959/? E/OwServiceUtils: Wallet error code: 51
10-16 10:32:33.584 21959-21959/? E/OwServiceUtils: Wallet error detail: To use this API, you must set the WalletOptions 'brand' field to ANDROID_PAY.
```

Anyone knows why and can help out?

**Comment by samtstern** [comment]
I am looking into this now, thank you for the report.  I have also noticed it on StackOverflow.

**Comment by samtstern** [comment]
This is a server issue on our end, we have a fix in place and are hoping to get it out today.  Thank you for noticing!

**Comment by samtstern** [comment]
@MaTriXy are you still seeing this issue?  I think it should be fixed by now.

**Comment by rahuls786** [comment]
i am still getting 

:10.252    1195-2018/com.google.android.gms E/Volley﹕ [157] BasicNetwork.performRequest: Unexpected response code 400 for https://wallet.google.com/payments/apis/instantbuy/android/v1/getWalletItems
10-22 14:07:10.253    1195-1325/com.google.android.gms W/BaseAppContext﹕ Using Auth Proxy for data requests.
10-22 14:07:10.254  11977-11977/com.google.android.gms.ui E/OwServiceUtils﹕ Wallet error code: 51
10-22 14:07:10.254  11977-11977/com.google.android.gms.ui E/OwServiceUtils﹕ Wallet error detail: Signing key fingerprints {FE:00:E2:90:99:6B:C8:3D:0B:9B:F7:6E:8F:76:35:A6:4F:4D:5D:BB} do not match our records for this app.

**Comment by MaTriXy** [comment]
@samtstern will check and update back.

**Comment by MaTriXy** [comment]
I get this Error now:

```
10-23 12:21:22.786 24512-30485/? E/Volley: [41510] BasicNetwork.performRequest: Unexpected response code 403 for https://wallet.google.com/payments/apis/instantbuy/android/v1/getWalletItems
10-23 12:21:22.799 27832-27832/? E/OwServiceUtils: Wallet error code: 12
```

But at least now i can see a msg saying that I need a US Address for that account.

**Comment by rahuls786** [comment]
@samtstern could you please look into above issue

**Comment by Freesoul1982** [comment]
@rahuls786 are you sure that you using the right keystore? debug vs release?

**Comment by Freesoul1982** [comment]
@samtstern @MaTriXy Now everything working alright , no error messages.

**Comment by mithilwcities** [comment]
I am not getting 'Buy with Android Pay' button instead it shows same old 'Buy with Google' (Google Wallet) button, even after increasing the Google Pay Services version.

**Comment by samtstern** [comment]
@mithilwcities make sure your `WalletFragmentStyle` looks like this:

``` java
WalletFragmentStyle walletFragmentStyle = new WalletFragmentStyle()
    .setBuyButtonText(WalletFragmentStyle.BuyButtonText.BUY_WITH)
    .setBuyButtonAppearance(WalletFragmentStyle.BuyButtonAppearance.ANDROID_PAY_DARK)
    .setBuyButtonWidth(WalletFragmentStyle.Dimension.MATCH_PARENT);
```

I have an update coming to this repo in a few days that will make that change, among other updates.

Also I am going to close this issue, as the original problem was resolved.

**Comment by mithilwcities** [comment]
On pressing on Android Pay button, I am getting following issue: "To make purchases using Android Pay,please set your cards in the android pay app". And the Android Pay App Downloaded from Google Play Store doesn't allow to add Credit Cards with sandbox credentials. Then how to test my app.

**Comment by samtstern** [comment]
You will need to add a real card to Android Pay, and then if you test your app using the sandbox you will not actually be charged.

**Comment by nak5ive** [comment]
I was receiving the same error (Wallet error code: 51) when attempting to launch the WalletFragment. The dialog would show for a split second then close. This error was also coming in tandem with an Android Pay error code 405, which indicates an incorrect signing certificate. I checked and double checked the fingerprint/package name were the same as registered in the developer console.

Eventually, the only way i was able to get past the error and successfully launch the dialog was to revert back to using the now deprecated ENVIRONMENT_SANDBOX constant instead of ENVIRONMENT_TEST, both when instantiating the google api client, as well as the wallet fragment options.

Now the dialog stay up. However I am only shown the error "To make purchases using Android Pay, please set your cards in the android pay app". We already have valid cards in the Android Pay app.

Can you double-check that this issue has not resurfaced?

**Comment by mithilwcities** [comment]
I am getting following error in my Production App:
Wallet error code: 51
Wallet error detail: You have not registered to use this API.

Is there anything I am missing?

**Comment by samtstern** [comment]
@mithilwcities please do not post the same comment on many issues.

Have you signed up to be an Android Pay merchant using this form: https://support.google.com/androidpay/merchant/contact/api_interest?rd=1 ?

**Comment by mithilwcities** [comment]
Hi Sam,

Sorry about doing that.

Regards,
Mithil
