### ISSUE TITLE
Trying to use the sample app getting a 405.

### ISSUE THREAD

**Issue by malcolmnguyen** [android-pay/androidpay-quickstart#7]
Trying to use the sample app and am getting a ERROR_CODE_MERCHANT_ACCOUNT_ERROR. This also happens on our own debug app and recently started showing up this week. The SHA1 keys match what is on the dev api console.

**Comment by jam0cam** [comment]
I am having the same issue. Oddly for me, the sample app works fine, but when I created a separate app with _exactly_ the same code, it's giving me that 405 error.

Might be worth noting that this issue only happened recently. 2-3 weeks ago, everything was working fine. Then I got a new laptop, and then I noticed this issue. I suspect that it could be the change in environment, but not sure why the sample app works, but my own project doesn't work. 

Also, this is the log I'm seeing: 

```
11-09 13:18:49.914 14773-14815/? E/Volley: [675] BasicNetwork.performRequest: Unexpected response code 400 for https://sandbox.google.com/payments/apis/instantbuy/android/v1/getWalletItems
11-09 13:18:49.915 14773-14824/? W/BaseAppContext: Using Auth Proxy for data requests.
11-09 13:18:49.915 7472-7472/? E/OwServiceUtils: Wallet error code: 51
11-09 13:18:49.915 7472-7472/? E/OwServiceUtils: Wallet error detail: You have not registered to use this API.
```

**Comment by jam0cam** [comment]
for others experiencing similar issues, you can try the following: 

instead of using ENVIRONMENT_TEST, try using ENVIRONMENT_SANDBOX. That may temporarily disable some issues you may have.

Apparently, ENVIRONMENT_TEST requires google play services 8.4+, which doesn't exist yet.

**Comment by malcolmnguyen** [comment]
This works now

**Comment by mithilwcities** [comment]
I am getting following error in my Production App:
Wallet error code: 51
Wallet error detail: You have not registered to use this API.

Is there anything I am missing?
